---
- name: Configuring Sinatra web application
  hosts: localhost
  gather_facts: false
  connection: local
  become: true
  user: ubuntu
  vars: 
    app_path: /home/ubuntu/sinatra-app    # Make sure to modify this path to desired application path
  tasks:
  # Tasks to update the system and install dependencies and caching for 1 hour
  - name: update system to latest state
    package: update_cache=true cache_valid_time=3600
    
  # Install base software development tools required for application to run smoothly  
  - name: Install dependencies
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - git-core 
      - curl 
      - libffi-dev
      - zlib1g-dev 
      - libreadline-dev 
      - libyaml-dev 
      - libsqlite3-dev 
      - sqlite3 
      - libxml2-dev 
      - libxslt1-dev 
      - libcurl4-openssl-dev 
      - bison
      - openssl
      - libyaml-dev
      - autoconf
      - python-pip
      - automake
      - libtool
      - pkg-config
      - bundler

  # Adding Ruby repository 
  - name: Add Brightbox PPA
    apt_repository: repo=ppa:brightbox/ruby-ng-experimental state=present
                 
  # Install Ruby 2.2 required for application              
  - name: Install Ruby
    apt: name={{ item }} state=present
    with_items:
     - ruby2.2
     
  # Install Sinatra gem for application   
  - name: Install some useful ruby gems
    gem: name={{ item }} state=present
    with_items:
      - sinatra 

  # Download the app and run bundle
  - name: downloading git repo
    git:
     repo: "https://github.com/rea-cruitment/simple-sinatra-app.git"
     dest: "{{ app_path }}"
     accept_hostkey: true
     version: master
    become: false

  - name: running bunle 
    bundler: 
     state: present
     chdir: "{{ app_path }}"
    become: false

  # Install nginx web server
  - name: install nginx
    package: 
     name: nginx
     state: present
 
  # Starting the nginx service
  - name: start nginx
    service:
     name: nginx
     enabled: true
     state: started
  
  # Adding proxy rules in nginx configuration file to allow traffic from 9292 to port 80
  - name: modify nginx config
    blockinfile: 
      path: "/etc/nginx/sites-available/default"
      insertafter: '^\s*location / {'
      content: |
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-NginX-Proxy true;
        proxy_pass http://127.0.0.1:9292;
    notify: restart_nginx
  
  # Handler to restart the nginx upon configuration change
  handlers:
  - name: restart_nginx
    service:
      name: nginx
      state: restarted

...
